### ISSUE TITLE
Caissabase 2024

### ISSUE THREAD

**Issue by woprandi** [franciscoBSalgueiro/encroisssant-site#4]
### Describe the feature

Available database to download from app offers Caissabase 2022. It would be cool to update it

**Comment by woprandi** [comment]
@franciscoBSalgueiro 
I downloaded latest Caissabase (27 april 2024) from http://caissabase.co.uk/
Converted to PGN with ScidVsPC
Imported to EnCroissant
Removed duplicates and empty games
The db3 file is here : https://drive.google.com/file/d/1i3hSWDEA3tiYwVvpa038Uhmp9Debhbj4/view?usp=sharing
I don't know if there are other tasks to do before replace the old one

**Comment by franciscoBSalgueiro** [comment]
Sorry for the delay, it's been updated now
